FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy ONLY .env.production (not .env.local)
COPY .env.production .env  


COPY . .


RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
