// import { Geist, Geist_Mono } from "next/font/google";
// import '../styles/global.css'; // Path goes up and into styles/

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Exclusive Household Staff",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import { Geist, Geist_Mono } from "next/font/google";
// import '../styles/global.css';
// import Image from 'next/image';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Exclusive Household Staff",
//   description: "Premium staffing solutions for elite households", // Updated description
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         {/* Add header with logo */}
//         <header className="fixed top-0 left-0 right-0 z-50 bg-white shadow-sm">
//           <div className="max-w-7xl mx-auto px-4 py-3 flex items-center">
//             <div className="flex items-center">
//               <Image
//                 src="/images/logo.png"
//                 alt="Exclusive Household Staff Logo"
//                 width={40}
//                 height={40}
//                 className="mr-3"
//               />
//               <h1 className="text-xl font-bold">Exclusive Household Staff</h1>
//             </div>
//           </div>
//         </header>
        
//         {/* Main content with padding to account for fixed header */}
//         <main className="pt-16">
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import '../styles/global.css';
import Image from 'next/image';
import Head from 'next/head';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Exclusive Household Staff",
  description: "Premium staffing solutions for elite households",
  icons: {
    icon: [
       { url: '/title_logo.png', type: 'image/png' }, // ✅ apna logo
    ],
    apple: [
      { url: '/title_logo.png' }, // ✅ iOS ke liye
    ],
  },
  manifest: '/site.webmanifest'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Additional head tags can go here */}
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Logo as the visual title */}
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}